# Generated by Django 3.0.6 on 2020-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
                ('company_page', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('high_price', models.CharField(default='', max_length=100)),
                ('low_price', models.CharField(default='', max_length=100)),
                ('now_price', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
                ('company_page', models.CharField(max_length=350)),
            ],
        ),
    ]
