# Generated by Django 3.0.6 on 2020-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('stock_list', models.CharField(max_length=100)),
                ('deposit_list', models.CharField(max_length=100)),
            ],
        ),
    ]
