# Generated by Django 3.0.6 on 2020-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_number', models.AutoField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=100)),
                ('b_content', models.TextField(default='')),
                ('b_photo', models.ImageField(default='photos/no_image.png', upload_to='photos/%Y/%m/%d')),
                ('b_hit', models.IntegerField(default=0)),
                ('b_date', models.DateTimeField(auto_now_add=True)),
                ('b_writer', models.CharField(max_length=100)),
            ],
        ),
    ]
